server:
  port: 8082

spring:
  application:
    name: user-service

  profiles:
    active: local

file:
  upload-dir: D:/Stay Ease/user-service/uploads/profile-images
  default-avatar: D:/Stay Ease/user-service/uploads/profile-images/default-avatar.png
  max-file-size: 5MB

feign:
  client:
    config:
      default:
        logger-level: FULL

logging:
  level:
    root: INFO
    com.stayease.user_service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.stayease.user_service.config.AuthClient: DEBUG
    com.stayease.user_service.config.BookingClient: DEBUG
    com.stayease.user_service.config.PropertyClient: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/stayease_user_db
    username: root
    password: 2000030757
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000

services:
  auth:
    url: http://localhost:8081
  property:
    url: http://localhost:8084
  booking:
    url: http://localhost:8085

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://test-db:3306/stayease_user_db
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000

services:
  auth:
    url: http://test-auth-service:8081
  property:
    url: http://test-property-service:8084
  booking:
    url: http://test-booking-service:8085

---
spring:
  config:
    activate:
      on-profile: cut

  datasource:
    url: jdbc:mysql://cut-db:3306/stayease_user_db
    username: cut_user
    password: cut_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 8000

services:
  auth:
    url: http://cut-auth-service:8081
  property:
    url: http://cut-property-service:8084
  booking:
    url: http://cut-booking-service:8085

---
spring:
  config:
    activate:
      on-profile: ete

  datasource:
    url: jdbc:mysql://ete-db:3306/stayease_user_db
    username: ete_user
    password: ete_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

services:
  auth:
    url: http://ete-auth-service:8081
  property:
    url: http://ete-property-service:8084
  booking:
    url: http://ete-booking-service:8085

---
spring:
  config:
    activate:
      on-profile: drt

  datasource:
    url: jdbc:mysql://drt-db:3306/stayease_user_db
    username: drt_user
    password: drt_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 7000
        read-timeout: 12000

services:
  auth:
    url: http://drt-auth-service:8081
  property:
    url: http://drt-property-service:8084
  booking:
    url: http://drt-booking-service:8085

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://prod-db:3306/stayease_user_db
    username: DBName
    password: DBPwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000

services:
  auth:
    url: http://auth-service
  property:
    url: http://property-service
  booking:
    url: http://booking-service